CONTRACTIONS_DICT = {"can`t": "can not",
                     "won`t": "will not",
                     "don`t": "do not",
                     "aren`t": "are not",
                     "i`d": "i would",
                     "couldn`t": "could not",
                     "shouldn`t": "should not",
                     "wouldn`t": "would not",
                     "isn`t": "is not",
                     "it`s": "it is",
                     "didn`t": "did not",
                     "weren`t": "were not",
                     "mustn`t": "must not",
                     }
